/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#97425d",
        "surface-bright": "#f7faf7",
        "primary-fixed-dim": "#8ed4bf",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d312f",
        "surface-variant": "#e0e3e0",
        "on-primary": "#ffffff",
        "primary": "#004537",
        "on-background": "#191c1b",
        "on-error": "#ffffff",
        "primary-fixed": "#aaf1da",
        "on-tertiary-fixed-variant": "#574500",
        "on-surface-variant": "#3f4945",
        "on-primary-fixed": "#002019",
        "inverse-on-surface": "#eff1ee",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f1",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dbd8",
        "on-tertiary-container": "#4f3d00",
        "secondary-container": "#ff97b4",
        "on-surface": "#191c1b",
        "tertiary": "#735c00",
        "on-secondary-fixed": "#3f001b",
        "background": "#f7faf7",
        "tertiary-fixed-dim": "#e9c349",
        "tertiary-container": "#cca730",
        "on-tertiary-fixed": "#241a00",
        "on-primary-fixed-variant": "#005141",
        "surface-container-highest": "#e0e3e0",
        "error-container": "#ffdad6",
        "surface": "#f7faf7",
        "surface-container": "#eceeeb",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#ffb1c5",
        "outline": "#6f7975",
        "on-secondary-container": "#7a2b46",
        "outline-variant": "#bfc9c4",
        "on-secondary-fixed-variant": "#792b46",
        "on-primary-container": "#8fd5bf",
        "secondary-fixed": "#ffd9e1",
        "inverse-primary": "#8ed4bf",
        "tertiary-fixed": "#ffe088",
        "surface-container-high": "#e6e9e6",
        "surface-tint": "#206a58",
        "primary-container": "#0f5e4d",
        "gold": "#D4AF37",
        "warm-ivory": "#F8F5F0",
        "rich-gold": "#D4AF37",
        "emerald-green": "#0F5E4D"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "3xl": "28px",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "base": "8px",
        "gutter": "24px",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Playfair Display", "serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
        "display-lg-mobile": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "fontWeight": "600" }]
      },
      keyframes: {
        shimmer: {
          '100%': { transform: 'translateX(100%)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        }
      },
      animation: {
        shimmer: 'shimmer 2s infinite',
        fadeInUp: 'fadeInUp 0.8s ease-out forwards',
        fadeIn: 'fadeIn 1s ease-out forwards',
        'fade-in-up-slow': 'fadeInUp 1.2s ease-out forwards',
      }
    },
  },
  plugins: [],
}
